// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuIKAuPEf0zWNuPh714GWxYhTlxSvFg8A',
    appId: '1:607282749922:web:3ea6d4548be0e64ec519bb',
    messagingSenderId: '607282749922',
    projectId: 'miniappfirebaseauth',
    authDomain: 'miniappfirebaseauth.firebaseapp.com',
    storageBucket: 'miniappfirebaseauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhh2MbF-yqDA0UPDsu_s_hvKSzn2MKJp0',
    appId: '1:607282749922:android:6e9812bb1c2e53f7c519bb',
    messagingSenderId: '607282749922',
    projectId: 'miniappfirebaseauth',
    storageBucket: 'miniappfirebaseauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmUxLUlU8oGtk9qU6GWebIdY21Vfqgcb0',
    appId: '1:607282749922:ios:8a49960d16266931c519bb',
    messagingSenderId: '607282749922',
    projectId: 'miniappfirebaseauth',
    storageBucket: 'miniappfirebaseauth.firebasestorage.app',
    iosBundleId: 'com.example.miniAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmUxLUlU8oGtk9qU6GWebIdY21Vfqgcb0',
    appId: '1:607282749922:ios:8a49960d16266931c519bb',
    messagingSenderId: '607282749922',
    projectId: 'miniappfirebaseauth',
    storageBucket: 'miniappfirebaseauth.firebasestorage.app',
    iosBundleId: 'com.example.miniAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuIKAuPEf0zWNuPh714GWxYhTlxSvFg8A',
    appId: '1:607282749922:web:9fd042a227883270c519bb',
    messagingSenderId: '607282749922',
    projectId: 'miniappfirebaseauth',
    authDomain: 'miniappfirebaseauth.firebaseapp.com',
    storageBucket: 'miniappfirebaseauth.firebasestorage.app',
  );

}